/* NESTA AULA, FAREMOS APENAS A CAPTURA DAS INFORMAÇÕES DO HTML, 
SEM MODIFICAR OU ADICIONAR E REMOVER ELEMENTOS */

// Acessando o objeto Window e Document do HTML


// BODY -> "Você poderia obter este elemento?"


// CAPTURANDO PELO TIPO DE ELEMENTO


// CAPTURANDO PELO ID


// CAPTURANDO PELA CLASSE


// CAPTURANDO TODOS OS ELEMENTOS EM UMA LISTA


    // CAPTURANDO TODOS OS ELEMENTOS, PERCORRENDO E ITERANDO